const number1 = 3;
const number2 = 7;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 5;
const payment = 2;
const amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const tests = 1;
const assignments = 6;
const final = 9;
const grade = (tests + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Zach';
const lastName = 'Giffen';
const fullName = firstName + ' ' + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 10;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 100;
const isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log(nickname);
console.log(typeof nickname);
